version: "3.7"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    container_name: next-saas-postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=next-saas
